FROM python:3.9-slim

WORKDIR /app

# Copiar requisitos Python
COPY src/ai_agent/requirements.txt ./requirements.txt

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código fonte do agente de IA
COPY src/ai_agent/ ./src/ai_agent/

# Comando para iniciar o agente de IA
CMD ["python", "/app/src/ai_agent/message_classifier.py"]